name: NGS_pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.10
  - salmon>=1.4 # Una version < 1 hace que falle
  - picard=2.25.6 # Otras versiones entran en conflicto con java
  - openjdk=11.0.9.1 # Si usas < 11.0.3.1 no carga los archivos
  - bowtie2=2.4.5
  - krakenuniq=1.0.2
  - star==2.7.4a
  - biopython==1.78
  - psutil
  - seaborn
  - numpy
  - pandas
  - matplotlib
  - star
  - bbmap
  - fq
  - fastqc
#  - sortmerna
#  - hisat2
#  - stringtie
  - bedtools
  - kraken2
  - krakentools
  - bracken
  - taxpasta
  - multiqc
#  - krona
#  - falco
#  - subread
#  - qualimap
#  - ucsc-bedclip
#  - rseqc
#  - ucsc-bedgraphtobigwig
#  - minimap2
#  - adapterremoval
#  - porechop
#  - filtlong
  - kaiju
#  - diamond
#  - fastp
  - nf-core
  - insilicoseq
  - rsem
  - pip:
      - umi_tools
      - pysam
#      - cutadapt
      - docker  # sudo groupadd docker && sudo usermod -aG docker $USER && newgrp docker
      - pydeseq2
      - pyyaml